### ISSUE TITLE
Graphite line protocol is broken.

### ISSUE THREAD

**Issue by lxnt** [dalmatinerdb/ddb_proxy#10]
Listeners die with calls to undefined function:
{undef,[{dp_index,add,[<<"collector2">>,<<5 ...

I think this is because of KeyBin in dp_line_proto.erl:29:

git blame dp_multiline_proto.erl:
556cbe2f (Heinz N. Gies 2016-09-04 19:14:06 +0200 32)     dp_index:add(Bucket, M),

git blame dp_line_proto.erl:
556cbe2f (Heinz N. Gies   2016-09-04 19:14:06 +0200 29)     dp_index:add(Bucket, KeyBin, Metric),

**Comment by Licenser** [comment]
you you please attach the full error line?

**Comment by lxnt** [comment]
Error in process <0.305.0> on node 'ddb_proxy@127.0.0.1' with exit value:
{undef,[{dp_index,add,[<<"collector2">>,<<5,108,111,99,97,108,6,114,97,110,100,111,109,8,100,105,99,101,114,111,108,108>>,#{key => [<<"local">>,<<"random">>,<<"diceroll">>],metric => [<<"local">>,<<"random">>,<<"diceroll">>],tags => [],time => 1474622130,value => 4}],[]},{dp_line_proto,decode_metric,2,[{file,"/dataloop/ddb_proxy/_build/deb/lib/ddb_proxy/src/dp_line_proto.erl"},{line,29}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{dp_line_proto,fold_lines,3,[{file,"/dataloop/ddb_proxy/_build/deb/lib/ddb_proxy/src/dp_line_proto.erl"},{line,12}]},{dp_tcp_listener,loop,4,[{file,"/dataloop/ddb_proxy/_build/deb/lib/ddb_proxy/src/dp_tcp_listener.erl"},{line,22}]}]}

**Comment by Licenser** [comment]
thanks, found and fixed.
