### ISSUE TITLE
Error using opentsdb listener

### ISSUE THREAD

**Issue by mqsquidy** [dalmatinerdb/ddb_proxy#13]
We currently are evaluating timeseries solutions and have looked at opentsdb. I noticed that dalmatinerdb offers a translation layer in ddb_proxy. I followed the instructions for single node setup but when I attempt to send opentsdb structured messages to ddb_proxy the telnet connection is terminated and I receive these errors in the crash log:

2016-10-10 12:49:56 =ERROR REPORT====
Error in process <0.307.0> on node 'ddb_proxy@127.0.0.1' with exit value:
{undef,[{dp_index,add,[<<"OpenTSDB">>,<<4,116,101,115,116,6,109,101,116,114,105,99,14,104,11
1,115,116,61,108,111,99,97,108,104,111,115,116>>,#{key => [<<"test">>,<<"metric">>,<<"host=l
ocalhost">>],metric => [<<"test">>,<<"metric">>],tags => [{<<>>,<<"host">>,<<"localhost">>}]
,time => 1476103793,value => 100}],[]},{dp_line_proto,decode_metric,2,[{file,"/dataloop/ddb_
proxy/_build/deb/lib/ddb_proxy/src/dp_line_proto.erl"},{line,29}]},{lists,foldl,3,[{file,"li
sts.erl"},{line,1262}]},{dp_line_proto,fold_lines,3,[{file,"/dataloop/ddb_proxy/_build/deb/l
ib/ddb_proxy/src/dp_line_proto.erl"},{line,9}]},{dp_tcp_listener,loop,4,[{file,"/dataloop/dd
b_proxy/_build/deb/lib/ddb_proxy/src/dp_tcp_listener.erl"},{line,22}]}]}
2016-10-10 12:49:56 =ERROR REPORT====
Ranch listener dp_otsdb_OpenTSDB_4242_tcp had connection process started with dp_tcp_listene
r:start_link/4 at <0.307.0> exit with reason: {undef,[{dp_index,add,[<<"OpenTSDB">>,<<4,116,
101,115,116,6,109,101,116,114,105,99,14,104,111,115,116,61,108,111,99,97,108,104,111,115,116

> > ,#{key => [<<"test">>,<<"metric">>,<<"host=localhost">>],metric => [<<"test">>,<<"metric">
> > ],tags => [{<<>>,<<"host">>,<<"localhost">>}],time => 1476103793,value => 100}],[]},{dp_lin
> > e_proto,decode_metric,2,[{file,"/dataloop/ddb_proxy/_build/deb/lib/ddb_proxy/src/dp_line_pro
> > to.erl"},{line,29}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{dp_line_proto,fold_li
> > nes,3,[{file,"/dataloop/ddb_proxy/_build/deb/lib/ddb_proxy/src/dp_line_proto.erl"},{line,9}]
> > },{dp_tcp_listener,loop,4,[{file,"/dataloop/ddb_proxy/_build/deb/lib/ddb_proxy/src/dp_tcp_li
> > stener.erl"},{line,22}]}]}

Any help would be greatly appreciated.

**Comment by Licenser** [comment]
HI looks like the latest fixes have not made it into the linux package yet (I'm guessing you're using that?).

@davecromberge can we build a new linux package for ddb_proxy?

In the meantime you can rather easy to build your own package. You need erlang (r18) installed on your system and then just clone and run `make deb-prepare`. (dave correct if I'm wrong here)

**Comment by mqsquidy** [comment]
Thx, we are using he latest debian package. I will try to compile it myself.

**Comment by davecromberge** [comment]
Hi @mqsquidy thanks for reporting this. 

I suspect that you are not using a Postgres index in your proxy, but are using the default index.  The default index is somewhat basic and does not support some commands such as `add`.  It's mainly for lookups.  The Postgres index has more comprehensive coverage.

I have uploaded a new version of the `ddb_proxy` package and have successfully tested OpenTSDB with the following config settings:

Update your `/etc/ddb_proxy/ddb_proxy.conf` as follows:

```
listeners.dp_otsdb.bucket = OpenTSDB
listeners.dp_otsdb.port = 4242
listeners.dp_otsdb.protocol = tcp

# Make sure you are using the postgres index and not the dqe_idx_ddb default index
idx.backend = dqe_idx_pg
```

Restart your `ddb_proxy` service:
`service ddb_proxy restart`

I will make sure that future debians do not use the default indexer and use Postgres instead. 

You can use the following packages for the latest versions of the Dalmatiner DB:

```
http://deb.project-fifo.net/releases/latest/dalmatinerdb_0.2.2_amd64.deb
http://deb.project-fifo.net/releases/latest/ddb-proxy_0.2.1_amd64.deb
http://deb.project-fifo.net/releases/latest/dalmatiner-frontend_0.2.1_amd64.deb
```

Let me know if you need any further assistance.

**Comment by Licenser** [comment]
The bug was this fix: https://github.com/dalmatinerdb/ddb_proxy/commit/dbd48653080095ab7c2893b4da3ac065d97eca15

when adding the dp_index I left that line with calling `add/3` instead of `add/2` linux packages were build prior to that commit I think.

**Comment by davecromberge** [comment]
That could be the case @Licenser.  
As an aside, I just installed the latest package and did not get the postgres indexer out of the box which caused `undef` errors when calling certain add functions with varying arity.  Once the indexer is updated and service restarted, it works as normal.

**Comment by mqsquidy** [comment]
I just now noticed, I used the instructions page on the site(https://dalmatiner.readme.io/docs/dp-installation) to install ddb_proxy and the docs read:

wget http://deb.project-fifo.net/releases/latest/ddb-proxy_0.2.0_amd64.deb
dpkg -i ddb-proxy_0.2.0_amd64.deb
service ddb_proxy start

I tried using both settings for the indexer(dqe_idx_pg and dqe_idx_ddb) with neither working, maybe due to the 0.2.0 version.

I will use version 0.2.1 and let you know the results.

Thank you all for the quick responses.

**Comment by davecromberge** [comment]
I've now updated the docs with the latest package versions.

**Comment by mqsquidy** [comment]
the new package 0.2.1 worked for me, thank you all for your help

**Comment by davecromberge** [comment]
@mqsquidy that's great, thanks for reporting the issue.  Enjoy DalmatinerDB!
